### ISSUE TITLE
Signin 시 리덕스로 로그인 여부 통합 (loginYn)

### ISSUE THREAD

**Issue by ssr03** [bookclubstory/bookclub-front#28]
리덕스로 로그인유무를 공통으로 관리하는 것은 어떨까요?

기존 소스와 비교해 보았습니다.

기존,
리덕스에 있는 loginInfo에 특정 속성의 값 길이를 체크하여 signinYn 로컬 변수를 설정하고 하위 컴포넌트에 props로 전달하는 방식이었습니다.

현재, 
 `src/modules/user/session.ts`에서
 `loginInfo.loginYn`으로 로그인 유무를 통합하여 사용하도록 하였습니다.

사용 예> `src/pages/bookpost/BookpostList.tsx` 파일
```let loginYn = useSelector((state: RootStateOrAny) => state.session.loginInfo.loginYn);```

이렇게 바꾸면 코드 복잡도를 좀 개선할 수 있을 것 같습니다.

**Comment by starrything** [comment]
아하! 그러면 Gnb.tsx 에서 하위 컴포넌트(SigninBlock.tsx)를 개선해 볼래요?

**Comment by starrything** [comment]
수정 내역 확인했습니다.
